// data.jsx
const products = [
  // Mobiles
  { id: 1, name: "Samsung Galaxy S23", price: 74999, description: "Latest Samsung smartphone with a stunning display and advanced features.", category: "Mobiles", inStock: 10, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/p/w/p/-original-imah4zp8tfzndmmh.jpeg?q=70&crop=false", onSale: true },
  { id: 2, name: "Apple iPhone 14", price: 99900, description: "Powerful A16 chip with exceptional camera capabilities.", category: "Mobiles", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/m/o/b/-original-imaghx9qkugtbfrn.jpeg?q=70&crop=false", onSale: false },
  { id: 3, name: "Google Pixel 7", price: 59999, description: "Smartphone with advanced AI features and top-notch camera.", category: "Mobiles", inStock: 8, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/i/a/r/-original-imagtrf9qm3dufq9.jpeg?q=70&crop=false", onSale: true },
  { id: 4, name: "OnePlus Nord 2", price: 29999, description: "Mid-range smartphone with flagship features.", category: "Mobiles", inStock: 15, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/w/k/-original-imagg2abzhxjckxu.jpeg?q=70&crop=false", onSale: false },
  { id: 5, name: "Xiaomi 12 Pro", price: 69999, description: "High-performance smartphone with impressive camera technology.", category: "Mobiles", inStock: 7, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/r/f/-original-imaghkvuhzwge3za.jpeg?q=70&crop=false", onSale: true },
  { id: 6, name: "Vivo X70 Pro", price: 64990, description: "Photography-focused smartphone with Zeiss optics.", category: "Mobiles", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/416/416/ku4ezrk0/mobile/u/z/i/x70-pro-v2105-vivo-original-imag7bq4eumqhgka.jpeg?q=70&crop=false", onSale: false },
  { id: 7, name: "Realme GT Master Edition", price: 27999, description: "Sleek design with powerful performance.", category: "Mobiles", inStock: 10, imageUrl: "https://rukminim2.flixcart.com/image/416/416/l3rmzrk0/mobile/5/k/h/-original-imagetme9qz26q4k.jpeg?q=70&crop=false", onSale: true },
  { id: 8, name: "Oppo Find X5", price: 69990, description: "Premium smartphone with unique design and features.", category: "Mobiles", inStock: 6, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/n/z/u/-original-imagndwg4v7crhhd.jpeg?q=70&crop=false", onSale: false },
  { id: 9, name: "Honor 50", price: 32999, description: "Stylish smartphone with solid performance.", category: "Mobiles", inStock: 8, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/t/d/q/200-5g-eli-nx9-honor-original-imah3cgq6ekfzxgu.jpeg?q=70&crop=false", onSale: false },
  { id: 10, name: "Nokia G50", price: 19999, description: "Affordable smartphone with 5G capabilities.", category: "Mobiles", inStock: 5, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/t/7/c/g42-5g-ta-1586-ds-nokia-original-imah3ry3f9tyqndm.jpeg?q=70&crop=false", onSale: true },

  // Electronics
  { id: 11, name: "Sony WH-1000XM5", price: 34999, description: "Industry-leading noise-canceling headphones.", category: "Electronics", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/2/j/l/-original-imah28h4mwkywgfu.jpeg?q=70&crop=false", onSale: false },
  { id: 12, name: "Apple iMac 24", price: 129900, description: "All-in-one desktop computer with stunning display.", category: "Electronics", inStock: 4, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/allinone-desktop/4/n/f/-original-imaguw4jacxcepeb.jpeg?q=70&crop=false", onSale: true },
  { id: 13, name: "LG OLED TV 55", price: 79999, description: "Cinematic experience with stunning picture quality.", category: "Electronics", inStock: 8, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/x/h/e/-original-imah2txrpjgvwh2k.jpeg?q=70&crop=false", onSale: true },
  { id: 14, name: "Dell UltraSharp Monitor", price: 29999, description: "High-resolution monitor ideal for creative professionals.", category: "Electronics", inStock: 3, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/monitor/6/0/0/-original-imagysfvpg8jw4bz.jpeg?q=70&crop=false", onSale: false },
  { id: 15, name: "Samsung Galaxy Tab S8", price: 74999, description: "Premium tablet with productivity features.", category: "Electronics", inStock: 5, imageUrl: "https://rukminim2.flixcart.com/image/416/416/xif0q/cases-covers/flip-cover/e/p/d/fk-30525-fashion-original-imag6x5sufypfffg.jpeg?q=70&crop=false", onSale: true },
  { id: 16, name: "JBL Flip 6", price: 10999, description: "Portable Bluetooth speaker with powerful sound.", category: "Electronics", inStock: 7, imageUrl: "https://rukminim2.flixcart.com/image/416/416/l23mhzk0/speaker/g/c/r/-original-imagdguhhtszn6am.jpeg?q=70&crop=false", onSale: false },
  { id: 17, name: "GoPro HERO10", price: 49999, description: "Compact action camera for adventurous captures.", category: "Electronics", inStock: 6, imageUrl: "https://rukminim2.flixcart.com/image/612/612/kuyf8nk0/sports-action-camera/p/e/z/black-waterproof-action-camera-with-front-lcd-and-touch-rear-original-imag7yg4haansvzn.jpeg?q=70", onSale: true },
  { id: 18, name: "Philips Hue Smart Bulbs", price: 4999, description: "Smart lighting solution for your home.", category: "Electronics", inStock: 4, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/smart-lighting/q/o/u/7-919215850898-led-philips-original-imaghf7grkwz55zv.jpeg?q=70", onSale: false },
  { id: 19, name: "Fitbit Versa 3", price: 19990, description: "Smartwatch with fitness tracking and health monitoring.", category: "Electronics", inStock: 2, imageUrl: "https://rukminim2.flixcart.com/image/612/612/ko0d6kw0/smartwatch/r/u/z/39-6-fb511glnv-android-ios-fitbit-original-imag2kfh9z5xg7bn.jpeg?q=70", onSale: true },
  { id: 20, name: "Razer Kraken Gaming Headset", price: 8999, description: "Comfortable headset with immersive sound.", category: "Electronics", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/612/612/ksw4ccw0/headphone/w/g/r/rockerz-450-boat-original-imag6cqqh49wjfy5.jpeg?q=70", onSale: false },

  // Clothing
  { id: 21, name: "VeBNoR", price: 1599, description: "Comfortable casual shirt with excellent support.", category: "Clothing", inStock: 20, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/c/y/v/xxl-st40-vebnor-original-imah4uzgbpwxzppr.jpeg?q=70", onSale: false },
  { id: 22, name: "Levi's Trucker Jacket", price: 5999, description: "Classic denim jacket for a timeless look.", category: "Clothing", inStock: 12, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/o/y/7/-original-imagyj957mgsagsf.jpeg?q=70", onSale: true },
  { id: 23, name: "Nike Dri-FIT T-Shirt", price: 2499, description: "Moisture-wicking t-shirt for active lifestyles.", category: "Clothing", inStock: 10, imageUrl: "https://rukminim2.flixcart.com/image/612/612/kl5hh8w0/t-shirt/s/7/p/l-checks-white-fuaark-original-imagyc9jzggpsuna.jpeg?q=70", onSale: false },
  { id: 24, name: "Puma Sports Shorts", price: 1999, description: "Comfortable shorts for workouts and leisure.", category: "Clothing", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/612/612/kjkbv680-0/short/z/o/6/xxl-58825301-puma-original-imafz3hbcgk42qeq.jpeg?q=70", onSale: true },
  { id: 25, name: "Zara Basic Sweater", price: 2999, description: "Soft and stylish sweater for casual wear.", category: "Clothing", inStock: 15, imageUrl: "https://rukminim2.flixcart.com/image/612/612/kgcl7680/sweatshirt/5/b/m/8-9-years-299-dllnt-hfs-black-8-9y-dongli-original-imafwhr4hsygnyze.jpeg?q=70", onSale: false },
  { id: 26, name: "H&M Denim Jeans", price: 3999, description: "Stylish jeans that fit perfectly.", category: "Clothing", inStock: 6, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/i/i/x/4-5-years-junepsboy-lblue-urbano-juniors-original-imagkhzbwqtgvpgt.jpeg?q=70", onSale: true },
  { id: 27, name: "Gap Classic Tee", price: 1499, description: "Soft cotton t-shirt for everyday wear.", category: "Clothing", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/4/a/5/m-tspk2301seagreen-cobb-italy-original-imagqkmzkkbbfgzg.jpeg?q=70", onSale: false },
  { id: 28, name: "Uniqlo Ultra Light Down Jacket", price: 5999, description: "Lightweight jacket that provides warmth without bulk.", category: "Clothing", inStock: 5, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/k/1/n/l-1-no-zipperhoodie-weartogo-original-imah5jgtnhh8b8ug.jpeg?q=70", onSale: true },
  { id: 29, name: "Tommy Hilfiger Polo Shirt", price: 2999, description: "Classic polo shirt for a smart-casual look.", category: "Clothing", inStock: 4, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/6/a/f/-original-imagwz2wujx9egcs.jpeg?q=70", onSale: false },
  { id: 30, name: "Calvin Klein Iconic Hoodie", price: 4499, description: "Comfortable and stylish hoodie for colder days.", category: "Clothing", inStock: 8, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/u/f/t/m-k10k113090yaf-calvin-klein-original-imahfkd5zezpxbyj.jpeg?q=70", onSale: true },

  // Accessories
  { id: 31, name: "Fossil Gen 6 Smartwatch", price: 19999, description: "Stylish smartwatch with fitness tracking features.", category: "Accessories", inStock: 10, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/c/q/y/51-05-bxio2007-bxio3001-bxsm2007-android-ios-beatxp-yes-original-imagxhwdzgggzpx8.jpeg?q=70", onSale: true },
  { id: 32, name: "Bose QuietComfort 45", price: 34999, description: "Noise-canceling headphones with superior sound quality.", category: "Accessories", inStock: 5, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/e/j/6/quietcomfort-wireless-noise-cancelling-headphones-bose-original-imagvshaddeftnpy.jpeg?q=70", onSale: false },
  { id: 33, name: "Ray-Ban Wayfarer Sunglasses", price: 13999, description: "Iconic sunglasses with UV protection.", category: "Accessories", inStock: 15, imageUrl: "https://rukminim2.flixcart.com/image/612/612/k8ho0i80/sunglass/p/y/v/50-0rb4105-601-ray-ban-original-imafqhhckngwjr9k.jpeg?q=70", onSale: true },
  { id: 34, name: "Samsung Galaxy Buds 2", price: 9999, description: "True wireless earbuds with active noise cancellation.", category: "Accessories", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/d/n/galaxy-buds2-pro-sm-r510nzaainu-sm-r510nzaains-samsung-original-imagsbshfhq2gbyr.jpeg?q=70", onSale: false },
  { id: 35, name: "Anker PowerCore 10000", price: 2999, description: "Compact portable charger for your devices.", category: "Accessories", inStock: 8, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/power-bank/q/q/g/powercore-10000-mah-pd-10000-a1334h11-anker-original-imagskwwhphkajur.jpeg?q=70", onSale: true },
  { id: 36, name: "Logitech MX Anywhere 3", price: 8999, description: "Compact wireless mouse for travel.", category: "Accessories", inStock: 7, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/mouse/1/m/o/-original-imagshgruzv87fxz.jpeg?q=70", onSale: false },
  { id: 37, name: "Amazon Echo Show 8", price: 12999, description: "Smart display with Alexa for your home.", category: "Accessories", inStock: 4, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/p/j/9/stand-base-stand-for-echo-show-8-1st-2nd-gen-desktop-holder-for-original-imahf7ghhgwhyeqc.jpeg?q=70", onSale: true },
  { id: 38, name: "Fitbit Inspire 2", price: 8999, description: "Fitness tracker with heart rate monitoring.", category: "Accessories", inStock: 0, imageUrl: "https://rukminim2.flixcart.com/image/312/312/khmbafk0/smart-band-tag/b/9/r/no-yes-fb418bkbk-android-ios-fitbit-yes-original-imafxhe4vhkbthzg.jpeg?q=70", onSale: false },
  { id: 39, name: "JBL Charge 5", price: 13999, description: "Portable Bluetooth speaker with deep bass.", category: "Accessories", inStock: 3, imageUrl: "https://rukminim2.flixcart.com/image/612/612/kwmfqfk0/speaker/l/p/u/-original-imag993z4h5z5byp.jpeg?q=70", onSale: true },
  { id: 40, name: "GoPro Hero 9", price: 44999, description: "Action camera for capturing all your adventures.", category: "Accessories", inStock: 5, imageUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sports-action-camera/y/r/u/-original-imahyxtgj2g8uqvn.jpeg?q=70", onSale: false },
];

export default products;
